modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Lothrazar/RootsClassic/issues"
license="MIT"

[[mods]]
modId="rootsclassic"
version="${file.jarVersion}"
displayName="Roots Classic"
displayURL="https://www.curseforge.com/minecraft/mc-mods/roots-classic"
updateJSONURL="https://raw.githubusercontent.com/Lothrazar/RootsClassic/trunk/1.16/update.json" 
authors="Elucent, Lothrazar, Mrbysco"
description='''
Classic port of Roots, the Druidic Magic Mod
'''
[[dependencies.rootsclassic]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"